config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  use_doorkeeper

  concern :votable do
    put :vote_up, on: :member
    put :vote_down, on: :member
    delete :vote_cancel, on: :member
  end

  concern :commentable do
    post :create_comment, on: :member
  end

  devise_for :users

  root to: 'questions#index'

  resources :questions, concerns: %i[votable commentable] do
    resources :subscriptions, only: %i[create destroy], shallow: true
    resources :answers, concerns: %i[votable commentable], shallow: true, only: %i[create update destroy] do
      patch :update_best, on: :member
    end
  end

  resources :attachments , only: %i[destroy]

  resources :links , only: %i[destroy]

  namespace :user do
    resources :rewards, only: :index
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :other_profiles, on: :collection
      end
      resources :questions, only: %i[index show destroy update create] do
        resources :answers, only: %i[show destroy update create], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord

  include VotableModel
  has_many :votes, dependent: :destroy, as: :votable
  has_many :comments, dependent: :destroy, as: :commentable

  has_many :subscriptions, dependent: :destroy
  has_many :users, through: :subscriptions, dependent: :destroy

  belongs_to :author, class_name: "User", optional: true 

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :reward, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, presence: true 

  after_create :calculate_reputation, :subscribe


  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end

  def subscribe
    author.subscriptions.create(question: self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource
  before_action :find_question, only: %i[show destroy update]

  def index
    @questions = Question.all
    render json: @questions
  end

  def show
    render json: @question
  end

  def create
    @question = Question.new(question_params.merge(author: current_user))
    if @question.save
      render json: @question
    else
      render json: { status: :unprocessable_entity }, status: :unprocessable_entity
    end
  end

  def destroy
    @question.destroy
    if @question.errors.any?
      render json: { status: :unprocessable_entity }, status: :unprocessable_entity
    else
      head :ok
    end
  end

  def update
    
    if @question.update(question_params)
      render json: @question
    else
      render json: { status: :unprocessable_entity }, status: :unprocessable_entity
    end
  end

  private

  def find_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [], links_attributes: [:id, :name, :url, :_destroy], reward_attributes: [:title, :image])    
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Votable
  include Commentable
  before_action :find_question, only: %i[show edit update destroy update_best subscribe subscribe_cancel]

  after_action :publish_question, only: %i[create]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @comment = Comment.new
    @answer.links.new
  end

  def new
    @question = Question.new
    @question.links.new
    @question.build_reward
  end

  def edit;  end

  def create
    @question = Question.new(question_params.merge(author: current_user))
    if @question.save
      redirect_to @question, notice: "Your question successfully created."
    else 
     render :new
    end
  end

  def update
    @comment = Comment.new
    @question.update(question_params)
  end

  def destroy
    @question.destroy
  end

  private
  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast( 
      'questions', 
      ApplicationController.render(
        partial: 'questions/question_for_index',
        locals: { question: @question }
        )
      )
  end

  def find_question
    @question = Question.with_attached_files.find(params[:id])
  end

  
  def question_params
    params.require(:question).permit(:title, :body, files: [], links_attributes: [:id, :name, :url, :_destroy], reward_attributes: [:title, :image])    
  end

  
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def add_author_to_links
    self.links.each do |link|
      link.author = current_user
    end
  end
end

app/views/questions/_form.html.slim
h1 class="q-title"= @question.title
p class="q-body"= @question.body

-if current_user&.author_of?(@question)
    p= link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: @question.id }
    p= link_to 'Destroy question', question_path(@question), method: :delete

= form_with model: @question, class: 'hidden', html: { id: "edit-question-#{@question.id}" } do |f|
  = f.label :title, 'Your question title'
  = f.text_area :title
  = f.label :body, 'Your question body'
  = f.text_area :body
  = f.submit 'Save'

app/views/questions/_form_link.html.slim
p Links:

#links
  = f.fields_for :links do |link|
    = render 'link_fields', f: link
  .links_to
    = link_to_add_association 'add link', f, :links

app/views/questions/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/questions/_question.html.slim
h1 class="q-title"= question.title
p class="q-body"= question.body

-if can?(:create_comment, Question)
  .create_comment
    =render 'comments/create_comment', resource: question


-if !question.reward.nil?
  p= question.reward.title
  -if question.reward.image.attached?
    =image_tag(question.reward.image, size: '64x64')

-if question.files.attached?
  -question.files.each do |file|
    p= link_to file.filename.to_s, url_for(file)

-if question.links.any?
  .links
    p Links:
    ul
      -question.links.each do |link|
        -if link.gist?
          li
            = link.name
            -if current_user&.author_of?(link.linkable)
              = link_to 'Delete link', link_path(link.id), class: 'destroy-link', method: :delete, remote: true
          script src="#{link.url}.js"
        -else
          li
            = link_to link.name, link.url
            -if current_user&.author_of?(link.linkable)
              = link_to 'Delete link', link_path(link.id), class: 'destroy-link', method: :delete, remote: true



-if current_user&.author_of?(question)
    p= link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: question.id }
    p= link_to 'Destroy question', question_path(@question), method: :delete

= form_with model: question, class: 'hidden', html: { id: "edit-question-#{question.id}" } do |f|
  = f.label :title, 'Your question title'
  = f.text_area :title
  = f.label :body, 'Your question body'
  = f.text_area :body
  = f.label :files
  = f.file_field :files, multiple: true
  -if question.files.attached?
        -question.files.each do |file|
          p 
            = link_to file.filename.to_s, url_for(file)
            = link_to "Delete file", attachment_path(file.id), class: "attached_file", method: :delete, :remote => true

  = render 'form_link', f: f
  = f.submit 'Save'

app/views/questions/_question_for_index.html.slim
p= link_to question.title, question_path(question)

app/views/questions/edit.html.slim
edit.html.slim

app/views/questions/index.html.slim
-if can?(:create, Question)
  p = link_to 'Ask question', new_question_path

-if can?(:read, Question)
  .questions-list
    -@questions.each do |question|
      = render "question_for_index", question: question  
  

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true

  =render 'form_link', f: f

  p Reward:
  p
    = f.fields_for :reward do |r|
      = r.label :title, 'Reward title'
      = r.text_field :title
      = r.label :image
      = r.file_field :image

  p  = f.submit 'Ask'

app/views/questions/show.html.slim
.question-errors
  = render 'shared/errors', resource: @question

.question-flash

.attachment-flash

.question
  =render @question

-if can?(:create, Subscription)
  =link_to 'Subscribe', question_subscriptions_path(@question), method: :post
-else
  =link_to 'Unsubscribe', subscription_path, method: :delete

-if @question.comments.any?
  h2= "Question's comments"
  =render 'comments/comments', resource: @question

.voting
  =render 'votes/vote', resource: @question

.answer-flash

-if can?(:read, Answer)
  .answers
    = render @question.answers.best_answer_first

.answer-errors
  = render 'shared/errors', resource: @answer

-if can?(:create, Answer)
  = form_with model: [@question, @answer], class: 'new-answer', data: { type: :html } do |f|
    p
      = f.label :body
      = f.text_area :body
    p
      = f.label :files
      = f.file_field :files, multiple: true, direct_upload: true 

      = render 'form_link', f: f


    p= f.submit 'To answer'

app/views/questions/update.js.erb
$('.question-errors').html("<%= render 'shared/errors', resource: @question %>");
<% if !@question.errors.present? %>
  $('.question').html('<%= j render @question %>');
  $('.question-flash').html("<%= j render 'shared/flash' %>");
<% end %>