config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  use_doorkeeper

  concern :votable do
    put :vote_up, on: :member
    put :vote_down, on: :member
    delete :vote_cancel, on: :member
  end

  concern :commentable do
    post :create_comment, on: :member
  end

  devise_for :users

  root to: 'questions#index'

  resources :questions, concerns: %i[votable commentable] do
    resources :subscriptions, only: %i[create destroy], shallow: true
    resources :answers, concerns: %i[votable commentable], shallow: true, only: %i[create update destroy] do
      patch :update_best, on: :member
    end
  end

  resources :attachments , only: %i[destroy]

  resources :links , only: %i[destroy]

  namespace :user do
    resources :rewards, only: :index
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :other_profiles, on: :collection
      end
      resources :questions, only: %i[index show destroy update create] do
        resources :answers, only: %i[show destroy update create], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include VotableModel
  has_many :votes, dependent: :destroy, as: :votable
  has_many :comments, dependent: :destroy, as: :commentable

  belongs_to :author, class_name: "User", optional: true 
  belongs_to :question

  has_many :links, dependent: :destroy, as: :linkable
  has_many_attached :files
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  
  scope :best_answer_first, -> { order(best: :desc, created_at: :asc) }

  validates :body, presence: true

  after_create :notify

  def choose_best
    ActiveRecord::Base.transaction do
      old_best_answer = question.answers.find_by(best: true)
      if old_best_answer && old_best_answer != self
        old_best_answer.update!(best: false)
        question.reward.user_id = nil if question.reward.present?
      end
      update!(best: true)
      author.rewards << question.reward if question.reward.present?
    end
  end

  private

  def notify
    NewAnswersJob.perform_now
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Votable
  include Commentable

  before_action :find_answer, only: %i[destroy update update_best]
  before_action :find_question, only: %i[create]
  after_action :publish_answer, only: %i[create]

  authorize_resource

  def create
    @answer = @question.answers.create(answer_params.merge(author: current_user))
    respond_to do |format|
      if @answer.save
        format.json { render json: @answer }
      else
        format.json { render json: @answer.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def update
    @comment = Comment.new
    @answer.update(answer_params)
    @question = @answer.question
  end

  def update_best 
    @comment = Comment.new
    @question = @answer.question
    @answer.choose_best
  end

  def destroy
    @question = @answer.question
    @answer.destroy
  end

  private 

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast( 
      "/questions/#{params[:id]}/answers",
      { answer: @answer } )  
  end

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def find_question
    @question = Question.with_attached_files.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:id, :name, :url, :_destroy])    
  end

end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_answer, only: %i[show destroy update]
  before_action :find_question, only: %i[create]
  authorize_resource
  
  def show
    render json: @answer
  end

  def create
    @answer = @question.answers.create(answer_params.merge(author: current_user))
    if @answer.save
      render json: @answer
    else
      render json: { status: :unprocessable_entity }, status: :unprocessable_entity
    end
  end

  def destroy
    @answer.destroy
    if @answer.errors.any?
      render json: { status: :unprocessable_entity }, status: :unprocessable_entity
    else
      head :ok
    end
  end

  def update
    if @answer.update(answer_params)
      render json: @answer
    else
      render json: { status: :unprocessable_entity }, status: :unprocessable_entity
    end
  end


  private

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:id, :name, :url, :_destroy])
  end

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def find_question
    @question = Question.with_attached_files.find(params[:question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
  def add_author_to_links
    self.links.each do |link|
      link.author = current_user
    end
  end
end

app/views/answers/_answer.html.slim
table
  tr
    -if answer.best?
      td class="a-best-body" style = "color: red" data = {answer_id: answer.id} 
        = answer.body
        .voting
          =render 'votes/vote', resource: answer
      -if can?(:update, answer) && can?(:destroy, answer)
        td= link_to 'Destroy answer', answer, class: 'destroy-answer', data: { confirm: 'Are you sure?' }, method: :delete, :remote => true
        td= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
      -if answer.files.attached?
        -answer.files.each do |file|
          td= link_to file.filename.to_s, url_for(file)
        

    -else
      td class="a-body" data = {answer_id: answer.id} 
        = answer.body
        .voting
          =render 'votes/vote', resource: answer
      -if answer.files.attached?
        -answer.files.each do |file|
          td= link_to file.filename.to_s, url_for(file)
      -if can?(:update_best, answer) && !answer.best?
        td= link_to 'Best', update_best_answer_path(answer), class: 'best-answer-link', data: { answer_id: answer.id }, method: :patch, :remote => true
      -if can?(:update, answer) && can?(:destroy, answer)
        td= link_to 'Destroy answer', answer, class: 'destroy-answer', data: { confirm: 'Are you sure?' }, method: :delete, :remote => true
        td= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
        

-if answer.links.any?
  .links
    p Links:
    ul
      -answer.links.each do |link|
        -if link.gist?
          li
            = link.name
            -if can?(:destroy, link)
              = link_to 'Delete link', link_path(link.id), class: 'destroy-link', method: :delete, remote: true
          script src="#{link.url}.js"

        -else
          li
            = link_to link.name, link.url
            -if can?(:destroy, link)
              = link_to 'Delete link', link_path(link.id), class: 'destroy-link', method: :delete, remote: true

-if can?(:create_comment, Answer)
  .create_comment
    =render 'comments/create_comment', resource: answer

-if answer.comments.any?
  h2= "Answer's comments"
  =render 'comments/comments', resource: answer




-if can?(:create, Answer)
  = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
    = f.label :body, 'Your answer'
    = f.text_area :body
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true 
    = render 'questions/form_link', f: f
    -if answer.files.attached?
          -answer.files.each do |file|
            p 
              = link_to file.filename.to_s, url_for(file)
              = link_to "Delete file", attachment_path(file.id), class: "attached_file", method: :delete, :remote => true

    = f.submit 'Save'

app/views/answers/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.check_box :_destroy
  = link_to_remove_association "remove link", f

app/views/answers/create.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>");
<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('.destroy-answer').bind('ajax:success', function() {     
  $(this).closest('tr').fadeOut();
  $('.answers').html('<%= j render @question.answers %>');
  $('.answer-flash').html("<%= j render 'shared/flash' %>");
});

app/views/answers/update.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>");
<% if !@answer.errors.present? %>
  $('.answers').html('<%= j render @question.answers %>');
  $('.answer-flash').html("<%= j render 'shared/flash' %>");
<% end %>

app/views/answers/update_best.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>");
<% if !@answer.errors.present? %>
  $('.answers').html('<%= j render @question.answers.best_answer_first %>');
  $('.answer-flash').html("<%= j render 'shared/flash' %>");
<% end %>